var Discord = require("discord.js");
var bot = new Discord.Client();
var random = 1;
//wainum = 67;
//husnum = 53;


var waifu = ["Alaia"];
waifu[1] = ["Rin"];
waifu[2] = ["Porin"];
waifu[3] = ["Anju"];
waifu[4] = ["Meiri "];
waifu[5] = ["Ishuna "];
waifu[6] = ["Meria "];
waifu[7] = ["Ciel "];
waifu[8] = ["Aillu "];
waifu[9] = ["Almira "];
waifu[10] = ["Patty "];
waifu[11] = ["Ennis "];
waifu[12] = ["Kuon "];
waifu[13] = ["Elaine "];
waifu[14] = ["Vanekiss "];
waifu[15] = ["Amis "];
waifu[16] = ["Anne Rose "];
waifu[17] = ["Lamia "];
waifu[18] = ["Rofia "];
waifu[19] = ["Charis "];
waifu[20] = ["Raaf "];
waifu[21] = ["Miannu "];
waifu[22] = ["Storie "];
waifu[23] = ["Chihaya "];
waifu[24] = ["Celine "];
waifu[25] = ["Mea "];
waifu[26] = ["Chloe "];
waifu[27] = ["Yomi "];
waifu[28] = ["Elizabeth "];
waifu[29] = ["Anastasia "];
waifu[30] = ["Hazuki "];
waifu[31] = ["Selena "];
waifu[32] = ["Laevateinn "];
waifu[33] = ["Tyrfing "];
waifu[34] = ["Meiriki "];
waifu[35] = ["Meruda "];
waifu[36] = ["Roza "];
waifu[37] = ["Eve "];
waifu[38] = ["Lucretia "];
waifu[39] = ["Suzuka "];
waifu[40] = ["Kanon "];
waifu[41] = ["Arber "];
waifu[42] = ["Sheina "];
waifu[43] = ["Mirishu "];
waifu[44] = ["Soreiyu "];
waifu[45] = ["Sheimei "];
waifu[46] = ["Tamamo "];
waifu[47] = ["Courage "];
waifu[48] = ["Kagura "];
waifu[49] = ["Fencer "];
waifu[50] = ["Chloe(Collab) "];
waifu[51] = ["Shaman "];
waifu[52] = ["Sheherazade "];
waifu[53] = ["Spica "];
waifu[54] = ["Caeda "];
waifu[55] = ["Peridot "];
waifu[56] = ["Deneb "];
waifu[57] = ["Lupinus "];
waifu[58] = ["Yaurus "];
waifu[59] = ["Chiruru "];
waifu[60] = ["Masamune "];
waifu[61] = ["Theona "];
waifu[62] = ["Sita "];
waifu[63] = ["Shekinah "];
waifu[64] = ["Lizbeth "];
waifu[65] = ["Dorothea "];
waifu[66] = ["Leida "];

var wl = ["http://i.imgur.com/Kbv7OsD.png"];
//first link for waifus
wl[1] = ["http://i.imgur.com/UTo4Fp0.png"];
wl[2] = ["http://i.imgur.com/xsoBGPt.png"];
wl[3] = ["http://i.imgur.com/gjBnF4W.png"];
wl[4] = ["http://i.imgur.com/URPrrYx.png"];
wl[5] = ["http://i.imgur.com/Y4Q3nDJ.png"];
wl[6] = ["http://i.imgur.com/OcwuFSj.png"];
wl[7] = ["http://i.imgur.com/5kMYNNH.png"];
wl[8] = ["http://i.imgur.com/ismwIks.png"];
wl[9] = ["http://i.imgur.com/yOb5GiZ.png"];
wl[10] = ["http://i.imgur.com/7RjsY1p.png"];
wl[11] = ["http://i.imgur.com/gEmWauj.png"];
wl[12] = ["http://i.imgur.com/eBcgbfe.png"];
wl[13] = ["http://i.imgur.com/gyrGWbM.png"];
wl[14] = ["http://i.imgur.com/WmZdcwM.png"];
wl[15] = ["http://i.imgur.com/dSsjyqV.png"];
wl[16] = ["http://i.imgur.com/yTgdP5K.png"];
wl[17] = ["http://i.imgur.com/7A5wM68.png"];
wl[18] = ["http://i.imgur.com/fhknWuC.png"];
wl[19] = ["http://i.imgur.com/Op4Z2g0.png"];
wl[20] = ["http://i.imgur.com/bacPmhr.jpg"];
wl[21] = ["http://i.imgur.com/rJujBUu.png"];
wl[22] = ["http://i.imgur.com/ULdw02c.png"];
wl[23] = ["http://i.imgur.com/S3yx0Jt.png"];
wl[24] = ["http://i.imgur.com/BMZbQIj.png"];
wl[25] = ["http://i.imgur.com/MH1P5pR.png"];
wl[26] = ["http://i.imgur.com/wpxwRi6.png"];
wl[27] = ["http://i.imgur.com/Iofvewq.png"];
wl[28] = ["http://i.imgur.com/B2V4Inl.png"];
wl[29] = ["http://i.imgur.com/ediVt8s.png"];
wl[30] = ["http://i.imgur.com/OKTQ6yq.png"];
wl[31] = ["http://i.imgur.com/nbTaCr8.jpg"];
wl[32] = ["http://i.imgur.com/sKsl5jU.png"];
wl[33] = ["http://i.imgur.com/2778FEy.jpg"];
wl[34] = ["http://i.imgur.com/gOe7x1e.jpg"];
wl[35] = ["http://i.imgur.com/X97IzJ0.jpg"];
wl[36] = ["http://i.imgur.com/Qe1Pc19.jpg"];
wl[37] = ["http://i.imgur.com/U3cI7HS.png"];
wl[38] = ["http://i.imgur.com/TMG1do7.jpg"];
wl[39] = ["http://i.imgur.com/BQgLeFi.jpg"];
wl[40] = ["http://i.imgur.com/RrbwTS6.png"];
wl[41] = ["http://i.imgur.com/BumurIC.png"];
wl[42] = ["http://i.imgur.com/DMGtjmx.png"];
wl[43] = ["http://i.imgur.com/3yPwjdJ.png"];
wl[44] = ["http://i.imgur.com/jzVkI7e.png"];
wl[45] = ["http://i.imgur.com/C3jiNLd.png"];
wl[46] = ["http://i.imgur.com/oXvuyCk.png"];
wl[47] = ["http://i.imgur.com/Meg0Ti7.png"];
wl[48] = ["http://i.imgur.com/j81oHMh.png"];
wl[49] = ["http://i.imgur.com/wVRwMHP.png"];
wl[50] = ["http://i.imgur.com/jxqngQh.jpg"];
wl[51] = ["http://i.imgur.com/DPcTlHa.png"];
wl[52] = ["http://i.imgur.com/r4Qz7h8.png"];
wl[53] = ["http://i.imgur.com/SyLwDM7.png"];
wl[54] = ["http://i.imgur.com/w3c6VIZ.png"];
wl[55] = ["http://i.imgur.com/hnUiR88.png"];
wl[56] = ["http://i.imgur.com/Pdmx60r.png"];
wl[57] = ["http://i.imgur.com/qBOLXqh.png"];
wl[58] = ["http://i.imgur.com/Vx9fmAq.png"];
wl[59] = ["http://i.imgur.com/NJzkOIx.png"];
wl[60] = ["http://i.imgur.com/IYBHKYq.jpg"];
wl[61] = ["http://i.imgur.com/vCq1574.jpg"];
wl[62] = ["http://i.imgur.com/Rj59Yig.jpg"];
wl[63] = ["http://i.imgur.com/qiFKkJz.png"];
wl[64] = ["http://i.imgur.com/RbCZnhj.png"];
wl[65] = ["http://i.imgur.com/Rf7ArBy.jpg"];
wl[66] = ["http://i.imgur.com/QeU7u4v.jpg"];


var husba = ["Alexis"];
husba[1] = ["Regart"];
husba[2] = ["Gain"];
husba[3] = ["Lucido"];
husba[4] = ["Rogi"];
husba[5] = ["Dios"];
husba[6] = ["Alfred"];
husba[7] = ["Rambert"];
husba[8] = ["Gato"];
husba[9] = ["Aqil"];
husba[10] = ["Sarauz"];
husba[11] = ["Michael"];
husba[12] = ["Leon"];
husba[13] = ["Yuan"];
husba[14] = ["Jake"];
husba[15] = ["Lish"];
husba[16] = ["Mizuchi"];
husba[17] = ["Kazahaya"];
husba[18] = ["Decel"];
husba[19] = ["Zangetsu"];
husba[20] = ["Rusia"];
husba[21] = ["Megistus"];
husba[22] = ["Dilga"];
husba[23] = ["Freed"];
husba[24] = ["Zahar"];
husba[25] = ["Veter"];
husba[26] = ["Gein"];
husba[27] = ["Vargas "];
husba[28] = ["Flamel "];
husba[29] = ["Magnus "];
husba[30] = ["Retzius "];
husba[31] = ["Baruto "];
husba[32] = ["Edgar "];
husba[33] = ["Reagen "];
husba[34] = ["Sabareta "];
husba[35] = ["Hayate "];
husba[36] = ["Freiz "];
husba[37] = ["Veros "];
husba[38] = ["Von Lee "];
husba[39] = ["Kadanoba "];
husba[40] = ["Lyle "];
husba[41] = ["Reimei "];
husba[42] = ["Kudanstein "];
husba[43] = ["Reaper "];
husba[44] = ["Golmaras "];
husba[45] = ["Monzein "];
husba[46] = ["Vincent "];
husba[47] = ["Grants "];
husba[48] = ["Victor "];
husba[49] = ["Zainn "];
husba[50] = ["Alba "];
husba[51] = ["Sieg "];
husba[52] = ["Ramesses "];


var hl = ["http://i.imgur.com/WSRzDeb.png"];
//first link for husbandos
hl[1] = ["http://i.imgur.com/HciJM2X.png"];
hl[2] = ["http://i.imgur.com/jFrWzhq.png"];
hl[3] = ["http://i.imgur.com/DEkoshd.png"];
hl[4] = [""];
hl[5] = [""];
hl[6] = [""];
hl[7] = [""];
hl[8] = [""];
hl[9] = [""];
hl[10] = [""];
hl[11] = [""];
hl[12] = [""];
hl[13] = [""];
hl[14] = [""];
hl[15] = [""];
hl[16] = [""];
hl[17] = [""];
hl[18] = [""];
hl[19] = [""];
hl[20] = [""];
hl[21] = [""];
hl[22] = [""];
hl[23] = [""];
hl[24] = [""];
hl[25] = [""];
hl[26] = [""];
hl[27] = [""];
hl[28] = [""];
hl[29] = [""];
hl[30] = [""];
hl[31] = [""];
hl[32] = [""];
hl[33] = [""];
hl[34] = [""];
hl[35] = [""];
hl[36] = [""];
hl[37] = [""];
hl[38] = [""];
hl[39] = [""];
hl[40] = [""];
hl[41] = [""];
hl[42] = [""];
hl[43] = [""];
hl[44] = [""];
hl[45] = [""];
hl[46] = [""];
hl[47] = [""];
hl[48] = [""];
hl[49] = [""];
hl[50] = [""];
hl[51] = [""];
hl[52] = [""];



bot.on("ready", () => {
  console.log("Morning!");
  console.log("There are " + waifu.length + " Waifus");
  console.log("There are " + husba.length + " Husbandos");
});

bot.login("MjQ5MjAyMzg4NjkzNTQ5MDU3.CxC-wA.co2hAbffE21eZOQRc-GRcaN6tUk");

bot.on("message", msg => {

  // Set the prefix
  let prefix = "!";
  // Exit and stop if it's not there
  if(!msg.content.startsWith(prefix)) return;
  if (msg.content.startsWith(prefix + "waifu")) {

    random = Math.round((Math.random() * (waifu.length -1)));
    console.log(random);
    msg.channel.sendMessage("Here's your Waifu! Her name is " + waifu[random] + ". Here's a picture <3 Please treat her well!" + wl[random]);
  }

  else if (msg.content.startsWith(prefix + "husbando")) {
    random = Math.round((Math.random() * (husba.length -1)));
    console.log(random);
    msg.channel.sendMessage("Here's your Husbando! His name is " + husba[random] + ". Here's a picture <3 Please treat him well!" + hl[random]);
  }
});
